### ISSUE TITLE
Source directories empty/are symbolic links?

### ISSUE THREAD

**Issue by ikmartin** [jonsterling/forest#6]
This seemed an inappropriate question for the forester email list as it pertains to this specific forest. I'd like to build the project locally in order to use the trees as reference for the forester markup language, but the assets, erct, theme and trees/public directories are empty upon cloning the project. I think this is because these are symbolic links to local directories.

Is there any chance the full source code for this project will ever be released? It'd be quite useful for people such as myself beginning to grow their own forests with forester. I did see two previous releases (v1.9 and v2.0) but these do not include many of the current trees; neither release includes the source code for the forester tutorial tree [jms-0052], for instance.

**Comment by jonsterling** [comment]
Hi! I think the problem is you need to get the submodules too — which can be done using the “recursive” option of git clone. Best,JonOn 7 Feb 2024, at 7:14 pm, Isaac Martin ***@***.***> wrote:﻿
This seemed an inappropriate question for the forester email list as it pertains to this specific forest. I'd like to build the project locally in order to use the trees as reference for the forester markup language, but the assets, erct, theme and trees/public directories are empty upon cloning the project. I think this is because these are symbolic links to local directories.
Is there any chance the full source code for this project will ever be released? It'd be quite useful for people such as myself beginning to grow their own forests with forester. I did see two previous releases (v1.9 and v2.0) but these do not include many of the current trees; neither release includes the source code for the forester tutorial tree [jms-0052], for instance.

**Comment by ikmartin** [comment]
Ah, that was it, thank you! I was completely unaware of this functionality.

**Comment by patrick-nicodemus** [comment]
I was also confused by this, as I was unaware of the Git submodule feature and Github itself does not make it easy to understand what these links mean (It's a blue link but nothing happens when you click on it, it's just a name and an inscrutable hash)

Would it be possible to extend the readme with a sentence explaining recursive git cloning, or `git submodule init; git submodule update`, or similar?
